"""add_message_types_and_file_metadata_to_chat

Revision ID: 138afdac49b9
Revises: a8f9b3c2d1e0
Create Date: 2025-11-21 00:42:01.255136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138afdac49b9'
down_revision: Union[str, None] = 'a8f9b3c2d1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    message_type_enum = sa.Enum('TEXT', 'IMAGE', 'PDF', 'AUDIO', name='messagetype')
    message_type_enum.create(op.get_bind(), checkfirst=True)
    
    # Add columns
    op.add_column('chat_messages', sa.Column('message_type', message_type_enum, nullable=True))
    op.add_column('chat_messages', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('chat_messages', sa.Column('file_size', sa.Integer(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE chat_messages SET message_type = 'TEXT' WHERE message_type IS NULL")
    
    # Make column non-nullable
    op.alter_column('chat_messages', 'message_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'file_size')
    op.drop_column('chat_messages', 'file_name')
    op.drop_column('chat_messages', 'message_type')
    
    # Drop the enum type
    sa.Enum(name='messagetype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
