"""add_company_blacklist_table

Revision ID: 51c34f412f6d
Revises: 138afdac49b9
Create Date: 2025-11-21 00:56:13.564022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c34f412f6d'
down_revision: Union[str, None] = '138afdac49b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consumer_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_blacklist_consumer_id'), 'company_blacklist', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_company_blacklist_id'), 'company_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_company_blacklist_supplier_id'), 'company_blacklist', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_blacklist_supplier_id'), table_name='company_blacklist')
    op.drop_index(op.f('ix_company_blacklist_id'), table_name='company_blacklist')
    op.drop_index(op.f('ix_company_blacklist_consumer_id'), table_name='company_blacklist')
    op.drop_table('company_blacklist')
    # ### end Alembic commands ###
