"""add_is_read_to_chat_messages

Revision ID: 6268b256099f
Revises: 21df8c52fe00
Create Date: 2025-11-19 23:44:32.444076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6268b256099f'
down_revision: Union[str, None] = '21df8c52fe00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('chat_messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE chat_messages SET is_read = false WHERE is_read IS NULL')
    # Make column non-nullable
    op.alter_column('chat_messages', 'is_read', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_read')
    # ### end Alembic commands ###
